### ISSUE TITLE
Requires Elm 0.19.1 but can run on 0.19.0

### ISSUE THREAD

**Issue by rupertlssmith** [chazsconi/elm-phoenix-ports#3]
I am working with a codebase that is using Elm 0.19.0. I tried compiling this for 0.19.0 and it works just fine, so I don't think there is any reason to restrict the package range to >= 0.19.1?

**Comment by chazsconi** [comment]
Hi @rupertlssmith - I set the version to 0.19.1 as this is what I had tested with, so I can be sure it works correctly.  But I am happy to merge your PR.

Is there a reason you cannot upgrade to 0.19.1?

Charles

**Comment by rupertlssmith** [comment]
Thanks. No particular reason not to upgrade to 0.19.1, its just that our CI build is currently on 0.19.0 and not something that I maintain, so I need to wait until someone else fixes it.

I think its good practice not to restrict packages to 0.19.1 unnecessarily.

**Comment by rupertlssmith** [comment]
Will you be publishing a new release with this fix in it?

**Comment by chazsconi** [comment]
Yes, I already did after I merged. https://package.elm-lang.org/packages/chazsconi/elm-phoenix-ports/latest/

Thanks

**Comment by chazsconi** [comment]
BTW - if you have any feedback about the library it would be great to have.  Also, were you originally using the https://github.com/saschatimme/elm-phoenix library and migrated to this when you switched to Elm 19?
